name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd cashflow
          flutter pub get

      - name: Analyze project source
        run: |
          cd cashflow
          flutter analyze

      - name: Run tests
        run: |
          cd cashflow
          flutter test

      - name: Build Android
        run: |
          cd cashflow
          flutter build apk --debug
